controllerMappings.addComponent("content/components", "menu", "html", "Displays a menu, usually at the top of a page", "Content App component;Menu");
controllerMappings.addComponent("content/components", "toggleMenu", "html", "Displays a toggle menu which will toggled by a button", "Content App component;Menu");
controllerMappings.addComponent("content/components", "button", "html", "Displays a Bootstrap button", "Content App component;Bootstrap component");
controllerMappings.addComponent("content/components", "pageBody", "html", "Displays the page body in a template", "Content App component;Template");
controllerMappings.addComponent("content/components", "templateBody", "html", "Displays the page template body in a theme template", "Content App component;Template");
controllerMappings.addComponent("content/components", "portlet", "html", "Portlet section, which allows apps to inject content", "Content App component;Template;Portlet");
controllerMappings.addComponent("content/components", "directoryIndex", "html", "Display directory list", "Content App component");
controllerMappings.addComponent("content/components", "pageTitle", "html", "Displays the page title in a template", "Content App component");
controllerMappings.addComponent("content/components", "breadcrumb", "html", "Displays the page breadcrumb", "Content App component;Bootstrap component");
controllerMappings.addComponent("content/components", "socialLinks", "html", "Displays the social links", "Content App component");