<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Recipients-tab-email-job</name>
   <tag></tag>
   <elementGuidId>1c056c18-ef74-456b-bef5-526de1613bbf</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#recipients</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recipients</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kademi-container&quot;)/div[@class=&quot;main-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main-content-inner&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;tabbable&quot;]/ul[@class=&quot;nav nav-tabs tab-bricky&quot;]/li[@class=&quot;even&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
