controllerMappings.addComponent("learner", "learningPortlet", "html", "Display a suggested module and a list of available modules", "Learning App");
controllerMappings.addComponent("learner/components", "myLearningModules", "html", "Display user's learning modules", "Learning App");
controllerMappings.addComponent("learner/components", "modulePage", "module", "Display elearning module page content", "Learning App");
controllerMappings.addComponent("learner/components", "modulePageToolbar", "module", "Display module page toolbar navigation", "Learning App");
controllerMappings.addComponent("learner/components", "moduleComplete", "module", "Display completion modal when completes a module", "Learning App");
controllerMappings.addComponent("learner/components", "modulePagePagination", "module", "Display module page pagination", "Learning App");
controllerMappings.addComponent("learner/components", "quizPage", "module", "Display elearning quiz page content", "Learning App");
controllerMappings.addComponent("learner/components", "moduleCalEventForm", "module", "Allows users to register for instructor led training modules", "Learning App");
controllerMappings.addComponent("learner/components", "scormContent", "module", "Displays SCORM content", "Learning App");
controllerMappings.addComponent("learner/components", "modulesTile", "html", "Display available modules for current user in tile format", "Learning App;Tile component");
