<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_embed-responsive-item</name>
   <tag></tag>
   <elementGuidId>827e990b-aea0-4bbb-8e92-c2a90386fc81</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>embed-responsive-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;market-apps-list&quot;)/div[@class=&quot;col-xl-2 col-lg-3 col-md-4 col-sm-4 col-xs-6  market-app&quot;]/a[1]/div[@class=&quot;thumbnail app-inner&quot;]/div[@class=&quot;embed-responsive embed-responsive-16by9 no-logo&quot;]/div[@class=&quot;embed-responsive-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
