<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_caret</name>
   <tag></tag>
   <elementGuidId>533b6104-ef40-43d0-9b34-4ce3ab6c54f4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-users&quot;)/thead[1]/tr[@class=&quot;odd&quot;]/th[5]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-sm btn-default dropdown-toggle&quot;]/span[@class=&quot;caret&quot;]</value>
   </webElementProperties>
</WebElementEntity>
